-- Baseline schema, captured via `pg_dump --schema-only` from the dev database.
--
-- On a fresh/empty database, Flyway runs this migration to create the full schema from
-- scratch. On the existing dev database (already has these tables from Hibernate's old
-- ddl-auto=update), spring.flyway.baseline-on-migrate=true skips running this file and just
-- records that we're already at version 1 - see application.properties.example.
--
-- From this point on, ddl-auto is set to "validate" (Hibernate checks entities match the
-- schema but never auto-alters it), so any future entity change needs a new
-- V2__description.sql migration here instead of relying on Hibernate to guess the DDL.
--
-- PostgreSQL database dump
--


-- Dumped from database version 16.11
-- Dumped by pg_dump version 16.11




--
-- Name: appointments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.appointments (
    id bigint NOT NULL,
    appointment_date date NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    end_time time(0) without time zone NOT NULL,
    patient_email character varying(255) NOT NULL,
    patient_name character varying(255) NOT NULL,
    patient_phone character varying(255),
    reason text NOT NULL,
    rejection_reason character varying(255),
    start_time time(0) without time zone NOT NULL,
    status character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    doctor_id bigint NOT NULL,
    patient_user_id bigint NOT NULL,
    CONSTRAINT appointments_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'CONFIRMED'::character varying, 'CANCELLED'::character varying, 'COMPLETED'::character varying, 'REJECTED'::character varying, 'NO_SHOW'::character varying])::text[])))
);


--
-- Name: appointments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.appointments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.appointments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: audit_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.audit_logs (
    id bigint NOT NULL,
    action character varying(100) NOT NULL,
    admin_email character varying(255) NOT NULL,
    admin_id bigint NOT NULL,
    admin_name character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    details text,
    target_id bigint,
    target_type character varying(50)
);


--
-- Name: audit_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.audit_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: doctor_schedules; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.doctor_schedules (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    day_of_week character varying(20) NOT NULL,
    end_time time(0) without time zone NOT NULL,
    is_available boolean NOT NULL,
    start_time time(0) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    doctor_id bigint NOT NULL
);


--
-- Name: doctor_schedules_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.doctor_schedules ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.doctor_schedules_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: doctor_specialties; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.doctor_specialties (
    doctor_id bigint NOT NULL,
    specialty_id bigint NOT NULL
);


--
-- Name: doctors; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.doctors (
    id bigint NOT NULL,
    address character varying(255),
    bio text,
    consultation_fee double precision NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(150) NOT NULL,
    experience_years integer NOT NULL,
    is_active boolean NOT NULL,
    license_number character varying(50) NOT NULL,
    name character varying(100) NOT NULL,
    phone character varying(20),
    profile_image character varying(255),
    updated_at timestamp(6) without time zone NOT NULL
);


--
-- Name: doctors_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.doctors ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.doctors_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: otps; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.otps (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(255) NOT NULL,
    expire_at timestamp(6) without time zone NOT NULL,
    is_used boolean NOT NULL,
    otp character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT otps_type_check CHECK (((type)::text = ANY ((ARRAY['EMAIL_VERIFICATION'::character varying, 'PASSWORD_RESET'::character varying])::text[])))
);


--
-- Name: otps_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.otps ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.otps_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: specialties; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.specialties (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description text,
    name character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);


--
-- Name: specialties_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.specialties ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.specialties_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: system_settings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.system_settings (
    id bigint NOT NULL,
    maintenance_message text,
    maintenance_mode boolean NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(255) NOT NULL,
    is_active boolean NOT NULL,
    is_verified boolean NOT NULL,
    name character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    phone character varying(255),
    profile_image character varying(255),
    role character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    lock_time timestamp(6) without time zone,
    failed_login_attempts integer DEFAULT 0,
    auth_provider character varying(255) NOT NULL,
    no_show_count integer DEFAULT 0 NOT NULL,
    booking_locked boolean DEFAULT false NOT NULL,
    has_password boolean DEFAULT true NOT NULL,
    cancel_count integer DEFAULT 0 NOT NULL,
    CONSTRAINT users_auth_provider_check CHECK (((auth_provider)::text = ANY ((ARRAY['LOCAL'::character varying, 'GOOGLE'::character varying])::text[]))),
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'DOCTOR'::character varying, 'PATIENT'::character varying])::text[])))
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: appointments appointments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.appointments
    ADD CONSTRAINT appointments_pkey PRIMARY KEY (id);


--
-- Name: audit_logs audit_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT audit_logs_pkey PRIMARY KEY (id);


--
-- Name: doctor_schedules doctor_schedules_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.doctor_schedules
    ADD CONSTRAINT doctor_schedules_pkey PRIMARY KEY (id);


--
-- Name: doctor_specialties doctor_specialties_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.doctor_specialties
    ADD CONSTRAINT doctor_specialties_pkey PRIMARY KEY (doctor_id, specialty_id);


--
-- Name: doctors doctors_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.doctors
    ADD CONSTRAINT doctors_pkey PRIMARY KEY (id);


--
-- Name: otps otps_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.otps
    ADD CONSTRAINT otps_pkey PRIMARY KEY (id);


--
-- Name: specialties specialties_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.specialties
    ADD CONSTRAINT specialties_pkey PRIMARY KEY (id);


--
-- Name: system_settings system_settings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.system_settings
    ADD CONSTRAINT system_settings_pkey PRIMARY KEY (id);


--
-- Name: doctors uk1xu5x0jae737xae254t4rgcd1; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.doctors
    ADD CONSTRAINT uk1xu5x0jae737xae254t4rgcd1 UNIQUE (license_number);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: specialties ukbhb8s9o5hv30lkbidtod9cixc; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.specialties
    ADD CONSTRAINT ukbhb8s9o5hv30lkbidtod9cixc UNIQUE (name);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: doctor_specialties fk8gbyvkfmm5a01nmd5jberd993; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.doctor_specialties
    ADD CONSTRAINT fk8gbyvkfmm5a01nmd5jberd993 FOREIGN KEY (specialty_id) REFERENCES public.specialties(id);


--
-- Name: doctor_specialties fkas1tsi4uakiu7q90rnvsgvhfv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.doctor_specialties
    ADD CONSTRAINT fkas1tsi4uakiu7q90rnvsgvhfv FOREIGN KEY (doctor_id) REFERENCES public.doctors(id);


--
-- Name: appointments fkmujeo4tymoo98cmf7uj3vsv76; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.appointments
    ADD CONSTRAINT fkmujeo4tymoo98cmf7uj3vsv76 FOREIGN KEY (doctor_id) REFERENCES public.doctors(id);


--
-- Name: doctor_schedules fkqptts4sun4tpv6elafrnrfeup; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.doctor_schedules
    ADD CONSTRAINT fkqptts4sun4tpv6elafrnrfeup FOREIGN KEY (doctor_id) REFERENCES public.doctors(id);


--
-- Name: otps fkseso6nlp9f5fbuilrngn3pbyi; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.otps
    ADD CONSTRAINT fkseso6nlp9f5fbuilrngn3pbyi FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: appointments fksvnkjcycyc8v0jeh1vklfsmm8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.appointments
    ADD CONSTRAINT fksvnkjcycyc8v0jeh1vklfsmm8 FOREIGN KEY (patient_user_id) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--


